image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t chadow-image .

deploy:
  stage: deploy
  script:
    - docker run -d --restart always -p 7777:7777 chadow-image
  only:
    - main
  tags:
    - shell
  shell: bash