stages:
  - deploy

deploy:
  stage: deploy
  script:
    - git pull origin main
    - mvn package
    - pgrep -f "java.*chadow" > /dev/null || true && kill $(pgrep -f "java.*chadow")
    - nohup java -jar --enable-preview target/chadow-1.0.0.jar --server 7777 > /dev/null 2>&1 &
  only:
    - main
  tags:
    - shell