stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t chadow-image .
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker run -d --restart always -p 7777:7777 chadow-image
  only:
    - main
  tags:
    - docker