stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker stop $(docker ps -a -q)
    - docker build -t chadow-image .
    - docker run -d --restart unless-stopped -p 7777:7777 chadow-image
  only:
    - main